### ISSUE TITLE
Error while performing pip install open_excel

### ISSUE THREAD

**Issue by kottakm** [mohameosam/open_excel#2]
**pip install open_excel**

> Collecting open_excel   Using cached open_excel-0.101a0.tar.gz (6.5 kB) Requirement already satisfied: openpyxl in /usr/lib/python2.7/site-packages (from open_excel) (2.6.4) Requirement already satisfied: jdcal in /usr/lib/python2.7/site-packages (from openpyxl->open_excel) (1.4.1) Requirement already satisfied: et_xmlfile in /usr/lib/python2.7/site-packages (from openpyxl->open_excel) (1.0.1) Building wheels for collected packages: open-excel   Building wheel for open-excel (setup.py) ... error   ERROR: Command errored out with exit status 1:    command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';
> __file__='"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nyWtv9
>        cwd: /tmp/pip-install-UB5LPQ/open-excel/   Complete output (14 lines):   /usr/lib/python2.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '0.101a' to '0.101a0'
>     normalized_version,   running bdist_wheel   running build   running build_py   creating build   creating build/lib   creating build/lib/open_excel   copying open_excel/__init__.py -> build/lib/open_excel   copying open_excel/open_excel.py -> build/lib/open_excel   copying open_excel/search_excel.py -> build/lib/open_excel   running build_scripts   creating build/scripts-2.7   error: open_excel: Is a directory  
> ----------------------------------------   ERROR: Failed building wheel for open-excel   Running setup.py clean for open-excel Failed to build open-excel Installing collected packages: open-excel
>     Running setup.py install for open-excel ... error
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';
> __file__='"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nTesj4/install-record.txt
> --single-version-externally-managed --compile --install-headers /usr/include/python2.7/open-excel
>          cwd: /tmp/pip-install-UB5LPQ/open-excel/
>     Complete output (14 lines):
>     /usr/lib/python2.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '0.101a' to '0.101a0'
>       normalized_version,
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib
>     creating build/lib/open_excel
>     copying open_excel/__init__.py -> build/lib/open_excel
>     copying open_excel/open_excel.py -> build/lib/open_excel
>     copying open_excel/search_excel.py -> build/lib/open_excel
>     running build_scripts
>     creating build/scripts-2.7
>     error: open_excel: Is a directory
>     ---------------------------------------- ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';
> __file__='"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nTesj4/install-record.txt
> --single-version-externally-managed --compile --install-headers /usr/include/python2.7/open-excel Check the logs for full command output.
>

**Comment by mohameosam** [comment]
yes, seems like I will have to revisit the  pip ripo. You can follow the manual install instructions in the meantime, really simple and straight forward.


    On Thursday, November 26, 2020, 05:03:52 AM PST, Murali Krishna Kottakota <notifications@github.com> wrote:  
 
 


pip install open_excel


Collecting open_excel Using cached open_excel-0.101a0.tar.gz (6.5 kB) Requirement already satisfied: openpyxl in /usr/lib/python2.7/site-packages (from open_excel) (2.6.4) Requirement already satisfied: jdcal in /usr/lib/python2.7/site-packages (from openpyxl->open_excel) (1.4.1) Requirement already satisfied: et_xmlfile in /usr/lib/python2.7/site-packages (from openpyxl->open_excel) (1.0.1) Building wheels for collected packages: open-excel Building wheel for open-excel (setup.py) ... error ERROR: Command errored out with exit status 1: command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';
file='"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-nyWtv9
cwd: /tmp/pip-install-UB5LPQ/open-excel/ Complete output (14 lines): /usr/lib/python2.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '0.101a' to '0.101a0'
normalized_version, running bdist_wheel running build running build_py creating build creating build/lib creating build/lib/open_excel copying open_excel/init.py -> build/lib/open_excel copying open_excel/open_excel.py -> build/lib/open_excel copying open_excel/search_excel.py -> build/lib/open_excel running build_scripts creating build/scripts-2.7 error: open_excel: Is a directory
---------------------------------------- ERROR: Failed building wheel for open-excel Running setup.py clean for open-excel Failed to build open-excel Installing collected packages: open-excel
Running setup.py install for open-excel ... error
ERROR: Command errored out with exit status 1:
command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';
file='"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-nTesj4/install-record.txt
--single-version-externally-managed --compile --install-headers /usr/include/python2.7/open-excel
cwd: /tmp/pip-install-UB5LPQ/open-excel/
Complete output (14 lines):
/usr/lib/python2.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing '0.101a' to '0.101a0'
normalized_version,
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/open_excel
copying open_excel/init.py -> build/lib/open_excel
copying open_excel/open_excel.py -> build/lib/open_excel
copying open_excel/search_excel.py -> build/lib/open_excel
running build_scripts
creating build/scripts-2.7
error: open_excel: Is a directory
---------------------------------------- ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';
file='"'"'/tmp/pip-install-UB5LPQ/open-excel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-nTesj4/install-record.txt
--single-version-externally-managed --compile --install-headers /usr/include/python2.7/open-excel Check the logs for full command output.

**Comment by t12nslookup** [comment]
setup.py:
```
import setuptools
#from setuptools import setup

setuptools.setup(
    name='open_excel',                      # The name of the PyPI-package (includes all Ansible Modules on the matter)
    version='0.101a',                         # Update the version number for new releases
    description='Ansible Modules to Search/Read an Excel file and register its content into an ansible list of dict',
    long_description='Two Ansible Modules, one to read excel files and the other to search for contents within the excel
 file. Check README documentation for more details',
    keywords='excel,search,spreadsheet',
    url='https://github.com/mohameosam/open_excel',
    author='Mohamed Abouahmed, Kovarus Inc., San Ramon, CA <mabouahmed@kovarus.com>',
    author_email='mohamedosam@gmail.com',
    license='GPL v3',
    packages=setuptools.find_packages(),
    python_requires='>=2.7',
    install_requires='openpyxl'
    #scripts=['open_excel/open_excel.py', 'open_excel/search_excel.py']  # The Ansible Modules included in the package
)
```

__init__.py:
```
from .open_excel import read_xl_content, update_xl_content, main
from .search_excel import search_xl_content, main
```

it's allowed me to build and install a package, but I've not tested that it works as expected :)

[open_excel-0.101a0.tar.gz](https://github.com/mohameosam/open_excel/files/5813465/open_excel-0.101a0.tar.gz)

**Comment by mohameosam** [comment]
Yes, seems like there is an issue in the setup file in the repo. I would just follow the manual install instructions, it should be a straight forward process. Try that out and let me know if you run into any issues there

On Thursday, January 14, 2021, 12:24 PM, Jon Adams <notifications@github.com> wrote:




setup.py:
import setuptools
#from setuptools import setup

setuptools.setup(
    name='open_excel',                      # The name of the PyPI-package (includes all Ansible Modules on the matter)
    version='0.101a',                         # Update the version number for new releases
    description='Ansible Modules to Search/Read an Excel file and register its content into an ansible list of dict',
    long_description='Two Ansible Modules, one to read excel files and the other to search for contents within the excel
 file. Check README documentation for more details',
    keywords='excel,search,spreadsheet',
    url='https://github.com/mohameosam/open_excel',
    author='Mohamed Abouahmed, Kovarus Inc., San Ramon, CA <mabouahmed@kovarus.com>',
    author_email='mohamedosam@gmail.com',
    license='GPL v3',
    packages=setuptools.find_packages(),
    python_requires='>=2.7',
    install_requires='openpyxl'
    #scripts=['open_excel/open_excel.py', 'open_excel/search_excel.py']  # The Ansible Modules included in the package
)

init.py:
from .open_excel import read_xl_content, update_xl_content, main
from .search_excel import search_xl_content, main

it's allowed me to build and install a package, but I've not tested that it works as expected :)

open_excel-0.101a0.tar.gz

**Comment by mohameosam** [comment]
Do a manual install. Just create a library directory under your Ansible code working directory, then place the .py files in there.

Example:
my_ansible_code/library/open_excel.py
my_ansible_code/library/search_excel.py

**Comment by Pink-s** [comment]
Hi ,
I have done manual installation but still this error. Could you please guide me on what can be done?
ERROR! couldn't resolve module/action 'search_excel'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/my_ansible_code/library/readme.yml': line 27, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    tasks:
      - name: Looking-up Device IP
