### ISSUE TITLE
open_excel is throwing error while reading or searching the excel sheet - please help

### ISSUE THREAD

**Issue by preethpuliyasseri** [mohameosam/open_excel#3]
Installed the open_excel and search_excel modules with the same example files from https://www.kovarus.com/blog/managing-microsoft-excel-sheets-from-within-red-hat-ansible/

-rw-r--r-- 1 root root 9259 Feb 22 13:21 device_list.xlsx
drwxr-xr-x 2 root root 4096 Feb 22 13:26 library
-rw-r--r-- 1 root root 2320 Feb 22 13:21 read_excel_example.yml
-rw-r--r-- 1 root root 1436 Feb 22 13:21 update_excel_example.yml
 
Inside the libarary, we have manually installed .py files

-rw-r--r-- 1 root root 16207 Feb 22 13:21 open_excel.py
-rw-r--r-- 1 root root  9288 Feb 22 13:21 search_excel.py

running the command "ansible-playbook read_excel_example.yml -vvv" shows the below result

ansible-playbook 2.10.6
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: read_excel_example.yml ************************************************************************************************************************************************************************************************************
1 plays in read_excel_example.yml
Serach For : R550

PLAY [Read Excel File] **********************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Looking-up Device IP] *****************************************************************************************************************************************************************************************************************
task path: /Scripts/testuser/examples/read_excel_example.yml:27
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448 `" && echo ansible-tmp-1614001433.42-25423-173112938742448="` echo /root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448 `" ) && sleep 0'
Using module file /Scripts/testuser/examples/library/search_excel.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-25363vSPLCd/tmpeClMib TO /root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/ /root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.search_excel', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_search_excel_payload_YW68JJ/ansible_search_excel_payload.zip/ansible/modules/search_excel.py", line 140, in <module>
  File "/usr/lib/python2.7/site-packages/openpyxl/__init__.py", line 6, in <module>
    from openpyxl.workbook import Workbook
  File "/usr/lib/python2.7/site-packages/openpyxl/workbook/__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "/usr/lib/python2.7/site-packages/openpyxl/workbook/workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "/usr/lib/python2.7/site-packages/openpyxl/worksheet/worksheet.py", line 396
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
                                                                                        ^
SyntaxError: invalid syntax
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1614001433.42-25423-173112938742448/AnsiballZ_search_excel.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.search_excel', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_search_excel_payload_YW68JJ/ansible_search_excel_payload.zip/ansible/modules/search_excel.py\", line 140, in <module>\n  File \"/usr/lib/python2.7/site-packages/openpyxl/__init__.py\", line 6, in <module>\n    from openpyxl.workbook import Workbook\n  File \"/usr/lib/python2.7/site-packages/openpyxl/workbook/__init__.py\", line 4, in <module>\n    from .workbook import Workbook\n  File \"/usr/lib/python2.7/site-packages/openpyxl/workbook/workbook.py\", line 7, in <module>\n    from openpyxl.worksheet.worksheet import Worksheet\n  File \"/usr/lib/python2.7/site-packages/openpyxl/worksheet/worksheet.py\", line 396\n    return f\"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}\"\n                                                                                        ^\nSyntaxError: invalid syntax\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by mohameosam** [comment]
Can you please share your code to understand what's going on
